config/routes.rb
Rails.application.routes.draw do
  get 'admins/sign_up' => redirect('/')
  devise_for :admins
  resources :areas
  resources :runners
  resources :orders
  resources :orders
  resources :orders
  root 'orders#index'
  get 'report' => 'home#index'
  post '/runners/pay', :to => 'runners#pay'

end

app/models/runner.rb
class Runner < ActiveRecord::Base
end

app/controllers/runners_controller.rb
class RunnersController < ApplicationController
  before_action :set_runner, only: [:show, :edit, :update, :destroy]

  # GET /runners
  # GET /runners.json
  def index
    @runners = Runner.all
    @runners.each do |x|
      @orderss = Order.where(runner_id: x.id)
      @orders = @orderss.where(paid: false)
      if @orders != nil
        @total = Array.new
          @orders.each do |z|
            @total << z.profit
          end
        
        @sum = 0
          @total.each do |s|
            @sum += s
          end
        
        x.balance = @sum
        x.save
      end
    end
  end

  # GET /runners/1
  # GET /runners/1.json
  def show
    @runner = Runner.find(@runner.id)
    if params[:filter]
      @a = params[:filter].to_date
      @ordersz = Order.where(runner_id: @runner.id)
      @orderss = @ordersz.where(c_date: @a)

    else
      @orderss = Order.where(runner_id: @runner.id)
    end
      @orders = @orderss.where(paid: false)
      @total = Array.new
      @orders.each do |x|
        @total << x.profit
      end
      @sum = 0
      @total.each do |s|
        @sum += s
      end
    @runner.balance = @sum
    @runner.save
  end

  # GET /runners/new
  def new
    @runner = Runner.new
  end

  # GET /runners/1/edit
  def edit
  end

  def pay
    if params[:id][1] != nil
        z = params[:id][1].to_date
        x = params[:id][0].to_i
        @runner = Runner.find(x)
        @today = Order.where(c_date: z)
        @sent = @today.where(runner_id: @runner)
        @clear = @sent.where(paid: false)
        @clear.each do |d|
          d.paid = true
          d.save
      end
    else
        x = params[:id][0].to_i
        @runner = Runner.find(x)
        @sent = Order.where(runner_id: @runner)
        @clear = @sent.where(paid: false)
        @clear.each do |d|
          d.paid = true
          d.save
        end
    end
    respond_to do |format|
        format.html { redirect_to :back, notice: 'Payment was successfully made.' }
        format.json { render :index, status: :created }
    end
  end

  # POST /runners
  # POST /runners.json
  def create
    @runner = Runner.new(runner_params)
    @runner.status = true
    @area = Area.find_by(name: @runner.area)
    @runner.area_id = @area.id
    respond_to do |format|
      if @runner.save
        format.html { redirect_to @runner, notice: 'Runner was successfully created.' }
        format.json { render :show, status: :created, location: @runner }
      else
        format.html { render :new }
        format.json { render json: @runner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /runners/1
  # PATCH/PUT /runners/1.json
  def update
    respond_to do |format|
      if @runner.update(runner_params)
        format.html { redirect_to @runner, notice: 'Runner was successfully updated.' }
        format.json { render :show, status: :ok, location: @runner }
      else
        format.html { render :edit }
        format.json { render json: @runner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /runners/1
  # DELETE /runners/1.json
  def destroy
    @runner.destroy
    respond_to do |format|
      format.html { redirect_to runners_url, notice: 'Runner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_runner
      @runner = Runner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def runner_params
      params.require(:runner).permit(:runner_name, :area_id, :area, :status, :balance)
    end
end

app/helpers/runners_helper.rb
module RunnersHelper
end

app/views/runners/_form.html.erb
<%= simple_form_for(@runner) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :runner_name %>
    <%= f.input :area, collection: [ "Setapak", "Mahkota Cheras", "Ampang", "Cheras", "PJ", "Bangsar", "KL", "Sri Petaling", "Subang Jaya"] %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/runners/edit.html.erb
<h1>Editing Runner</h1>

<%= render 'form' %>

<%= link_to 'Show', @runner %> |
<%= link_to 'Back', runners_path %>

app/views/runners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All the Runners</h1>

<table>
  <thead>
    <tr>
      <th>Runner name</th>
      <th>Area</th>
      <th>Status</th>
      <th>Balance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @runners.each do |runner| %>
      <tr>
        <td><%=link_to runner.runner_name, runner %></td>
        <td><%= runner.area %></td>
        <td><%= runner.status %></td>
        <td>RM <%= runner.balance %></td>
        <td><%= link_to 'Edit', edit_runner_path(runner) %></td>
        <% if runner.balance == 0 %>
        <td><%= link_to 'Destroy', runner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Runner', new_runner_path, class: "alert button" %>

app/views/runners/new.html.erb
<h1>New Runner</h1>

<%= render 'form' %>

<%= link_to 'Back', runners_path %>

app/views/runners/show.html.erb
<p id="notice"><%= notice %></p>

<h3>
  <%= @runner.runner_name %>
</h3>

<p>
  <strong>Area:</strong>
  <%= @runner.area %>
</p>

<p>
  <strong>Order Sent:</strong>
  <%= @orders.count %>
</p>
        <div class="column large-4">
          <%= form_tag(runner_path, :method => "get", id: "datefilter") do %>
          <%= date_field_tag :filter, params[:filter], class: "span2", id: "dp1" %>

          </div>
           <div class="column large-8">
            <%= button_tag "Filter", class: "small" %>
            <% end %>
        </div>

<h4>Kena Bayar = 
	RM<%= @runner.balance %>
</h4>
<% if @runner.balance != 0 %>
	  <%= form_tag(runners_pay_path, :method => "post", id: "paid") do %>
      <%= hidden_field :id, params[:runner], :value => @runner.id %>
      <%= button_tag "Clear ALL!", class: "success button", data: { confirm: 'Are you sure?' } %>
      <% end %>
<% end %>
<% if params[:filter] %>
    <%= form_tag(runners_pay_path, :method => "post", id: "paid") do %>
      <%= hidden_field :id, params[:runner], :value => @runner.id %>
      <%= hidden_field :id, params[:date], :value => params[:filter] %>
      <%= button_tag "Clear TODAY ONLY!", class: "alert button", data: { confirm: 'Are you sure?' } %>
      <% end %>
<% end %>
<table>
  <thead>
    <tr>
      <th>Order</th>
      <th>Date</th>
      <th>Subtotal</th>
      <th>Cost</th>
      <th>Total Sales</th>
      <!-- <th>Delivery</th> -->
      <!-- <th>Runner</th> -->
      <!-- <th>Profit</th> -->
      <th>Cash in Hand</th>
      <th>Status</th>
      <!-- <th>Discount</th> -->
      <th>Area</th>
      <th>Runner</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= link_to order.order_id, order %></td>
        <td><%= order.c_date %></td>
        <td><%= order.subtotal %></td>
        <td><%= order.cost %></td>
        <td><%= order.sales %></td>
        <!-- <td><%= order.delivery %></td> -->
        <!-- <td><%= order.runner %></td> -->
        <td><%= order.profit %></td>
        <!-- <td><%= order.gst %></td> -->
        <% if order.paid == true %>
          <td>Cleared</td>
        <% else %>
          <td>Not Clear</td>
        <% end %>
        <!-- <td><%= order.discount %></td> -->
        <% if order.area_id != nil %>
        <% @area = Area.find(order.area_id) %>
        <td><%= @area.name %></td>
        <% else %>
        <td><%= order.area_id %></td>
        <% end %> 
        <td><%=  order.runner %></td>
           </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', runners_path %>