config/routes.rb
Rails.application.routes.draw do
  get 'admins/sign_up' => redirect('/')
  devise_for :admins
  resources :areas
  resources :runners
  resources :orders
  resources :orders
  resources :orders
  root 'orders#index'
  get 'report' => 'home#index'
  post '/runners/pay', :to => 'runners#pay'

end

app/models/order.rb
class Order < ActiveRecord::Base
	def self.search(search)
	  where("order_id ILIKE ?", "%#{search}%")
	end
	def self.filter(filter)
		where(c_date: filter)
 	end

 	def self.daily(filter)
		where("status_time ILIKE ?", "%#{filter}%")
 	end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    if params[:search]
      @orders = Order.search(params[:search]).order("created_at ASC").paginate(:page => params[:page], :per_page => 10)
    elsif params[:filter]
      @a = params[:filter].to_date
      @orderss = Order.where(c_date: @a).order('created_at ASC')
      @orders = @orderss.paginate(:page => params[:page], :per_page => 20)
    else
      @orders = Order.all.order('created_at DESC')
      @orders = @orders.paginate(:page => params[:page], :per_page => 10)
    end
  end

  def all
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @runners = Runner.all
    @runnerlist = Array.new
    @runners.each do |z|
      @runnerlist << z.runner_name
    end
    @areas = Area.all
    @arealist = Array.new
    @areas.each do |x|
      @arealist << x.name
    end
    # byebug
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.paid = false
      if @order.c_date == nil
        @order.c_date = Date.today
      end
    @beforegst = @order.subtotal+@order.delivery
    @order.gst = @beforegst*0.06
      if @order.discount != nil or @order.discount != 0
        @beforegst = @beforegst-@order.discount
      end
    @order.sales = @order.gst+@beforegst
    @order.profit = @order.sales-@order.cost
    @runner = Runner.find_by(runner_name: @order.runner)
    @order.runner_id = @runner.id
    @area = Area.find_by(name: @order.area)
    @order.area_id = @area.id
    respond_to do |format|
      if @order.save
        format.html { redirect_to orders_path, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @orders }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:order_id, :sales, :cost, :delivery, :runner_id, :profit, :gst, :discount, :area_id, :subtotal, :c_date, :area, :runner)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= simple_form_for(@order) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :order_id, label: "Order Number", as: :string %>
    <%= f.input :subtotal, as: :currency %>
    <%= f.input :cost, as: :currency %>
    <%= f.input :delivery, label: "Delivery", as: :currency, input_html: {value: f.object.delivery || '0'} %>
    <%= f.input :discount, label: "Discount Value (Not %)", as: :currency, input_html: {value: f.object.discount || '0'}  %>
    <%= f.input :runner, collection: @runnerlist %>
    <%= f.input :area, collection: @arealist %>
    <%= f.input :c_date, label: "Date (Leave empty if same day)", as: :date, html5: true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "success button", label: "Submit" %>
  </div>
<% end %>

app/views/orders/all.html.erb
<p id="notice"><%= notice %></p>


<div class="row large-12 panel">
  <h1>RunningMan Homemade POS</h1>
  


<table>
  <thead>
    <tr>
      <th>Order</th>
      <th>Date</th>
      <th>Subtotal</th>
      <!-- <th>Cost</th> -->
      <th>Total Sales</th>
      <th>Delivery</th>
      <th>Runner</th>
      <!-- <th>Profit</th> -->
      <th>Gst</th>
      <th>Discount</th>
      <th>Area</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= link_to order.order_id, order %></td>
        <td><%= order.c_date %></td>
        <td><%= order.subtotal %></td>
        <!-- <td><%= order.cost %></td> -->
        <td><%= order.sales %></td>
        <td><%= order.delivery %></td>
        <td><%= order.runner_id %></td>
        <!-- <td><%= order.profit %></td> -->
        <td><%= order.gst %></td>
        <td><%= order.discount %></td>
        <td><%= order.area_id %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path, class: "alert button" %>
</div>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<% if current_admin %>

  <h1>RunningMan Homemade POS</h1>
  
<div class="column panel large-12">
  <%= link_to 'Runner List', runners_path, class: "info button" %>
  <%= link_to 'Reports', report_path, class: "success button" %>
  <%= link_to 'Areas', areas_path, class: "secondary button" %>
</div>
        <div class="column large-6">
          <div class="column large-8">
            <%= form_tag(orders_path, :method => "get", id: "search-form") do %>
            <%= text_field_tag :search, params[:search], placeholder: "Search Order Number here...", autofocus: true %>
          </div>
          <div class="column large-4">
            <%= button_tag "Search", class: "small success" %>
            <% end %>
          </div>
        </div>
        <div class="column large-6">
          <div class="column large-8">
          <%= form_tag(orders_path, :method => "get", id: "datefilter") do %>
          <%= date_field_tag :filter, params[:filter], class: "span2", id: "dp1" %>

          </div>
           <div class="column large-4">
            <%= button_tag "Filter", class: "small" %>
            <% end %>
          </div>
        </div>
    
<h5><%= will_paginate @orders %></h5>
<table>
  <thead>
    <tr>
      <th>Order</th>
      <th>Date</th>
      <!-- <th>Subtotal</th> -->
      <th>Cost</th>
      <th>Total Sales</th>
      <!-- <th>Delivery</th> -->
      <th>Runner</th>
      <!-- <th>Profit</th> -->
      <!-- <th>Gst</th> -->
      <th>Status</th>
      <!-- <th>Discount</th> -->
      <th>Area</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= link_to order.order_id, order %></td>
        <td><%= order.c_date %></td>
        <!-- <td><%= order.subtotal %></td> -->
        <td><%= order.cost %></td>
        <td><%= order.sales %></td>
        <!-- <td><%= order.delivery %></td> -->
        <td><%= order.runner %></td>
        <!-- <td><%= order.profit %></td> -->
        <!-- <td><%= order.gst %></td> -->
        <% if order.paid == true %>
          <td>Cleared</td>
        <% else %>
          <td>Not Clear</td>
        <% end %>
        <!-- <td><%= order.discount %></td> -->
        <% if order.area_id != nil %>
        <% @area = Area.find(order.area_id) %>
        <td><%= @area.name %></td>
        <% else %>
        <td><%= order.area_id %></td>
        <% end %>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<h5><%= will_paginate @orders %></h5>
<br>

<%= link_to 'New Order', new_order_path, class: "alert button" %>
<% end %>

app/views/orders/new.html.erb
<div class="row panel">
	<h1>New Order</h1>

	<%= render 'form' %>

	<%= link_to 'Back', orders_path %>
</div>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order:</strong>
  <%= @order.order_id %>
</p>


<p>
  <strong>Subtotal:</strong>
  <%= @order.subtotal %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @order.cost %>
</p>

<p>
  <strong>Delivery:</strong>
  <%= @order.delivery %>
</p>

<p>
  <strong>Total Sales:</strong>
  <%= @order.sales %>
</p>

<p>
  <strong>Runner:</strong>
  <%= @order.runner %>
</p>

<p>
  <strong>Profit:</strong>
  <%= @order.profit %>
</p>

<p>
  <strong>Gst:</strong>
  <%= @order.gst %>
</p>

<p>
  <strong>Discount:</strong>
  <%= @order.discount %>
</p>

<p>
  <strong>Area:</strong>
  <%= @order.area %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>