config/routes.rb
Rails.application.routes.draw do
  get 'admins/sign_up' => redirect('/')
  devise_for :admins
  resources :areas
  resources :runners
  resources :orders
  resources :orders
  resources :orders
  root 'orders#index'
  get 'report' => 'home#index'
  post '/runners/pay', :to => 'runners#pay'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "RunningMan HomeMade POS" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div class="row panel">
      <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
       <p class="navbar-text pull-right">
        <% if admin_signed_in? %>
          Logged in as <strong><%= current_admin.email %></strong>.
          <%= link_to 'Edit profile', edit_admin_registration_path, :class => 'navbar-link, small alert button' %> |
          <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link, small info button'  %>
        <% else %>
          <!-- <%= link_to "Sign up", new_admin_registration_path, :class => 'navbar-link, small secondary button'  %> | -->
          <%= link_to "Login", new_admin_session_path, :class => 'navbar-link, small success button'  %>
        <% end %>
        </p>
      <%= link_to 'Popo punya rumah', root_path, class: "alert button" %>
      <%= yield %>
    </div>
    <a href="/vender" data-no-turbolink="true">
  </body>
</html>